import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'ar';

const originalTextNodes = new WeakMap<Text, string>();

const uiTranslations: Record<string, { en: string; ar: string }> = {
  'Vue d’ensemble': { en: 'Overview', ar: 'نظرة عامة' },
  'Établissements': { en: 'Establishments', ar: 'المؤسسات' },
  'Avis reçus': { en: 'Reviews', ar: 'التقييمات' },
  'Avis clients': { en: 'Customer reviews', ar: 'تقييمات العملاء' },
  'Fidélité': { en: 'Loyalty', ar: 'الولاء' },
  'Programme fidélité': { en: 'Loyalty program', ar: 'برنامج الولاء' },
  'Promotions': { en: 'Promotions', ar: 'العروض' },
  'Analytics': { en: 'Analytics', ar: 'التحليلات' },
  'Statistiques': { en: 'Statistics', ar: 'الإحصائيات' },
  'Menu': { en: 'Menu', ar: 'القائمة' },
  'Paramètres': { en: 'Settings', ar: 'الإعدادات' },
  'Tableau de bord': { en: 'Dashboard', ar: 'لوحة التحكم' },
  'Espace de gestion': { en: 'Management workspace', ar: 'مساحة الإدارة' },
  'Gérer mes établissements': { en: 'Manage my establishments', ar: 'إدارة مؤسساتي' },
  'Se déconnecter': { en: 'Sign out', ar: 'تسجيل الخروج' },
  'Scanner fidélité': { en: 'Loyalty scanner', ar: 'ماسح الولاء' },
  'Ouvrir': { en: 'Open', ar: 'فتح' },
  'Copier': { en: 'Copy', ar: 'نسخ' },
  'Annuler': { en: 'Cancel', ar: 'إلغاء' },
  'Enregistrer': { en: 'Save', ar: 'حفظ' },
  'Modifier': { en: 'Edit', ar: 'تعديل' },
  'Supprimer': { en: 'Delete', ar: 'حذف' },
  'Ajouter': { en: 'Add', ar: 'إضافة' },
  'Créer': { en: 'Create', ar: 'إنشاء' },
  'Rechercher': { en: 'Search', ar: 'بحث' },
  'Filtrer': { en: 'Filter', ar: 'تصفية' },
  'Exporter': { en: 'Export', ar: 'تصدير' },
  'Voir tout': { en: 'View all', ar: 'عرض الكل' },
  'Voir plus': { en: 'View more', ar: 'عرض المزيد' },
  'Chargement…': { en: 'Loading…', ar: 'جارٍ التحميل…' },
  'Chargement...': { en: 'Loading...', ar: 'جارٍ التحميل...' },
  'Aucun résultat': { en: 'No results', ar: 'لا توجد نتائج' },
  'Aucun établissement sélectionné': { en: 'No establishment selected', ar: 'لم يتم اختيار مؤسسة' },
  'Mon établissement': { en: 'My establishment', ar: 'مؤسستي' },
  'Avis & Réputation': { en: 'Reviews & Reputation', ar: 'التقييمات والسمعة' },
  'Expérience client': { en: 'Customer experience', ar: 'تجربة العميل' },
  'Performance': { en: 'Performance', ar: 'الأداء' },
  'Clients fidélisés': { en: 'Loyal customers', ar: 'العملاء المخلصون' },
  'Nouveaux avis': { en: 'New reviews', ar: 'تقييمات جديدة' },
  'Note moyenne': { en: 'Average rating', ar: 'متوسط التقييم' },
  'Derniers avis clients': { en: 'Latest customer reviews', ar: 'أحدث تقييمات العملاء' },
  'Répondre': { en: 'Reply', ar: 'الرد' },
  'Réponse': { en: 'Response', ar: 'الرد' },
  'Récompenses': { en: 'Rewards', ar: 'المكافآت' },
  'Clients': { en: 'Customers', ar: 'العملاء' },
  'Membres': { en: 'Members', ar: 'الأعضاء' },
  'Points': { en: 'Points', ar: 'النقاط' },
  'Récompense': { en: 'Reward', ar: 'مكافأة' },
  'Campagnes': { en: 'Campaigns', ar: 'الحملات' },
  'Aujourd’hui': { en: 'Today', ar: 'اليوم' },
  'Cette semaine': { en: 'This week', ar: 'هذا الأسبوع' },
  'Ce mois-ci': { en: 'This month', ar: 'هذا الشهر' },
  '7 derniers jours': { en: 'Last 7 days', ar: 'آخر 7 أيام' },
  '30 derniers jours': { en: 'Last 30 days', ar: 'آخر 30 يوماً' },
  '3 mois': { en: '3 months', ar: '3 أشهر' },
  '6 mois': { en: '6 months', ar: '6 أشهر' },
  '12 mois': { en: '12 months', ar: '12 شهراً' },
  'Total': { en: 'Total', ar: 'الإجمالي' },
  'Activé': { en: 'Enabled', ar: 'مفعّل' },
  'Désactivé': { en: 'Disabled', ar: 'معطّل' },
  'Actif': { en: 'Active', ar: 'نشط' },
  'Inactif': { en: 'Inactive', ar: 'غير نشط' },
  'Oui': { en: 'Yes', ar: 'نعم' },
  'Non': { en: 'No', ar: 'لا' },
  'Fermer': { en: 'Close', ar: 'إغلاق' },
  'Continuer': { en: 'Continue', ar: 'متابعة' },
  'Retour': { en: 'Back', ar: 'رجوع' },
  'Sélectionner': { en: 'Select', ar: 'اختيار' },
  'Nom': { en: 'Name', ar: 'الاسم' },
  'Téléphone': { en: 'Phone', ar: 'الهاتف' },
  'Email': { en: 'Email', ar: 'البريد الإلكتروني' },
  'Adresse': { en: 'Address', ar: 'العنوان' },
  'Statut': { en: 'Status', ar: 'الحالة' },
  'Date': { en: 'Date', ar: 'التاريخ' },
  'Actions': { en: 'Actions', ar: 'الإجراءات' },
  'Utilisateur': { en: 'User', ar: 'المستخدم' },
  'Responsable': { en: 'Manager', ar: 'المسؤول' },
  'Administrateur': { en: 'Administrator', ar: 'المشرف' },
  'Bienvenue': { en: 'Welcome', ar: 'مرحباً' },
  'Aperçu': { en: 'Overview', ar: 'نظرة عامة' },
  'Aucun': { en: 'None', ar: 'لا يوجد' },
  'Enregistrer les modifications': { en: 'Save changes', ar: 'حفظ التغييرات' },
  'Nouvelle récompense': { en: 'New reward', ar: 'مكافأة جديدة' },
  'Créer une campagne': { en: 'Create campaign', ar: 'إنشاء حملة' },
  'Ajouter un client': { en: 'Add customer', ar: 'إضافة عميل' },
  'Générer un QR code': { en: 'Generate QR code', ar: 'إنشاء رمز QR' },
};

const expandedUiTranslations: Record<string, { en: string; ar: string }> = {
  'Erreur établissements:': { en: 'Establishments error:', ar: 'خطأ المؤسسات:' },
  'Erreur équipe:': { en: 'Team error:', ar: 'خطأ الفريق:' },
  'Erreur profils:': { en: 'Profiles error:', ar: 'خطأ الملفات الشخصية:' },
  'Erreur types IA:': { en: 'AI types error:', ar: 'خطأ أنواع الذكاء الاصطناعي:' },
  'Erreur statistiques globales:': { en: 'Global statistics error:', ar: 'خطأ الإحصائيات العامة:' },
  'Erreur plans:': { en: 'Plans error:', ar: 'خطأ الخطط:' },
  'Erreur abonnements:': { en: 'Subscriptions error:', ar: 'خطأ الاشتراكات:' },
  'Erreur facturation:': { en: 'Billing error:', ar: 'خطأ الفوترة:' },
  'Erreur vue Admin:': { en: 'Admin view error:', ar: 'خطأ عرض المشرف:' },
  'Tous les établissements': { en: 'All establishments', ar: 'جميع المؤسسات' },
  'Établissement': { en: 'Establishment', ar: 'المؤسسة' },
  'Ajouter un établissement': { en: 'Add establishment', ar: 'إضافة مؤسسة' },
  'Gérer les responsables': { en: 'Manage managers', ar: 'إدارة المسؤولين' },
  'Voir les avis': { en: 'View reviews', ar: 'عرض التقييمات' },
  'Générer un rapport': { en: 'Generate report', ar: 'إنشاء تقرير' },
  'Clients fidélisés': { en: 'Loyal customers', ar: 'العملاء المخلصون' },
  'Événements analytics': { en: 'Analytics events', ar: 'أحداث التحليلات' },
  'Paiements échoués': { en: 'Failed payments', ar: 'المدفوعات الفاشلة' },
  'Rechercher un établissement...': { en: 'Search for an establishment...', ar: 'ابحث عن مؤسسة...' },
  'Essayez une autre recherche.': { en: 'Try another search.', ar: 'جرّب بحثاً آخر.' },
  'Créez votre premier établissement pour commencer.': { en: 'Create your first establishment to get started.', ar: 'أنشئ مؤسستك الأولى للبدء.' },
  'Erreur lors du chargement de la fidélité.': { en: 'Error loading loyalty data.', ar: 'حدث خطأ أثناء تحميل بيانات الولاء.' },
  'Erreur génération QR scanner:': { en: 'Scanner QR generation error:', ar: 'خطأ في إنشاء رمز QR للماسح:' },
  'Établissement enregistré.': { en: 'Establishment saved.', ar: 'تم حفظ المؤسسة.' },
  'Wi-Fi enregistré.': { en: 'Wi-Fi saved.', ar: 'تم حفظ Wi-Fi.' },
  'Sélectionne uniquement un fichier PDF.': { en: 'Select a PDF file only.', ar: 'اختر ملف PDF فقط.' },
  'Sélectionne un PDF ou une photo de menu.': { en: 'Select a PDF or menu photo.', ar: 'اختر ملف PDF أو صورة للقائمة.' },
  'Erreur pendant l’analyse du menu.': { en: 'Error while analyzing the menu.', ar: 'حدث خطأ أثناء تحليل القائمة.' },
  'Impossible d’enregistrer le menu.': { en: 'Unable to save the menu.', ar: 'تعذر حفظ القائمة.' },
  'Nom et catégorie obligatoires.': { en: 'Name and category are required.', ar: 'الاسم والفئة مطلوبان.' },
  'Le nombre de points par unité monétaire doit être supérieur à 0.': { en: 'Points per currency unit must be greater than 0.', ar: 'يجب أن يكون عدد النقاط لكل وحدة نقدية أكبر من 0.' },
  'Paramètres fidélité enregistrés.': { en: 'Loyalty settings saved.', ar: 'تم حفظ إعدادات الولاء.' },
  'Le nom de la récompense est obligatoire.': { en: 'Reward name is required.', ar: 'اسم المكافأة مطلوب.' },
  'Les points requis doivent être un entier supérieur à 0.': { en: 'Required points must be an integer greater than 0.', ar: 'يجب أن تكون النقاط المطلوبة عدداً صحيحاً أكبر من 0.' },
  'Erreur lors de l’ajout de la récompense.': { en: 'Error adding reward.', ar: 'حدث خطأ أثناء إضافة المكافأة.' },
  'Erreur lors de la modification de la récompense.': { en: 'Error editing reward.', ar: 'حدث خطأ أثناء تعديل المكافأة.' },
  'Équipe': { en: 'Team', ar: 'الفريق' },
  'Lien scanner copié.': { en: 'Scanner link copied.', ar: 'تم نسخ رابط الماسح.' },
  'Génération du lien sécurisé…': { en: 'Generating secure link…', ar: 'جارٍ إنشاء الرابط الآمن…' },
  'QR code du scanner fidélité': { en: 'Loyalty scanner QR code', ar: 'رمز QR لماسح الولاء' },
  'Enregistrer le profil': { en: 'Save profile', ar: 'حفظ الملف الشخصي' },
  'Choisir le PDF ou les photos du menu': { en: 'Choose the PDF or menu photos', ar: 'اختر ملف PDF أو صور القائمة' },
  'Analyse du menu…': { en: 'Analyzing menu…', ar: 'جارٍ تحليل القائمة…' },
  'Analyser avec l’IA': { en: 'Analyze with AI', ar: 'تحليل بالذكاء الاصطناعي' },
  'Création du menu…': { en: 'Creating menu…', ar: 'جارٍ إنشاء القائمة…' },
  'Créer ce menu': { en: 'Create this menu', ar: 'إنشاء هذه القائمة' },
  'Menu numérique': { en: 'Digital menu', ar: 'القائمة الرقمية' },
  'Design premium IA généré.': { en: 'Premium AI design generated.', ar: 'تم إنشاء تصميم فاخر بالذكاء الاصطناعي.' },
  'Impossible de générer le design IA.': { en: 'Unable to generate AI design.', ar: 'تعذر إنشاء التصميم بالذكاء الاصطناعي.' },
  'Création du design…': { en: 'Creating design…', ar: 'جارٍ إنشاء التصميم…' },
  'Générer le design premium': { en: 'Generate premium design', ar: 'إنشاء تصميم فاخر' },
  'Éditorial, élégant et très lisible.': { en: 'Editorial, elegant and highly readable.', ar: 'تحريري وأنيق وسهل القراءة.' },
  'Premium, raffiné avec accents dorés.': { en: 'Premium and refined with gold accents.', ar: 'فاخر وراقٍ مع لمسات ذهبية.' },
  'Sobre, moderne et épuré.': { en: 'Minimal, modern and clean.', ar: 'بسيط وعصري ونقي.' },
  'Épuré, élégant et très lisible.': { en: 'Clean, elegant and highly readable.', ar: 'نقي وأنيق وسهل القراءة.' },
  'Restaurant premium avec détails dorés.': { en: 'Premium restaurant with gold details.', ar: 'مطعم فاخر بتفاصيل ذهبية.' },
  'Photos produits et présentation visuelle.': { en: 'Product photos and visual presentation.', ar: 'صور المنتجات والعرض البصري.' },
  'Ambiance lounge, sombre et sophistiquée.': { en: 'Dark and sophisticated lounge atmosphere.', ar: 'أجواء لاونج داكنة وراقية.' },
  'Désactiver': { en: 'Disable', ar: 'تعطيل' },
  'Sans description': { en: 'No description', ar: 'بدون وصف' },
  'Clients fidélité': { en: 'Loyalty customers', ar: 'عملاء الولاء' },
  'Événements enregistrés': { en: 'Recorded events', ar: 'الأحداث المسجلة' },
  'Page établissement': { en: 'Establishment page', ar: 'صفحة المؤسسة' },
  'Accès direct au programme fidélité': { en: 'Direct access to loyalty program', ar: 'وصول مباشر إلى برنامج الولاء' },
  'Accès direct au menu': { en: 'Direct access to menu', ar: 'وصول مباشر إلى القائمة' },
  'Accès direct à la section avis': { en: 'Direct access to reviews section', ar: 'وصول مباشر إلى قسم التقييمات' },
  'Veuillez remplir le nom de l’établissement.': { en: 'Please enter the establishment name.', ar: 'يرجى إدخال اسم المؤسسة.' },
  'Veuillez sélectionner le type de l’établissement.': { en: 'Please select the establishment type.', ar: 'يرجى اختيار نوع المؤسسة.' },
  'Établissement créé avec succès.': { en: 'Establishment created successfully.', ar: 'تم إنشاء المؤسسة بنجاح.' },
  'Création...': { en: 'Creating...', ar: 'جارٍ الإنشاء...' },
  'Créer l’établissement': { en: 'Create establishment', ar: 'إنشاء المؤسسة' },
  'Aucun responsable': { en: 'No manager', ar: 'لا يوجد مسؤول' },
  'Créez le premier responsable d’un établissement.': { en: 'Create the first manager for an establishment.', ar: 'أنشئ أول مسؤول لمؤسسة.' },
  'Aucun employé': { en: 'No employee', ar: 'لا يوجد موظف' },
  'Créez le premier employé d’un établissement.': { en: 'Create the first employee for an establishment.', ar: 'أنشئ أول موظف لمؤسسة.' },
  'Veuillez sélectionner un établissement.': { en: 'Please select an establishment.', ar: 'يرجى اختيار مؤسسة.' },
  'Le code employé doit contenir au moins 4 caractères.': { en: 'Employee code must contain at least 4 characters.', ar: 'يجب أن يحتوي رمز الموظف على 4 أحرف على الأقل.' },
  'Impossible de créer l’employé.': { en: 'Unable to create employee.', ar: 'تعذر إنشاء الموظف.' },
  'Le mot de passe doit contenir au moins 6 caractères.': { en: 'Password must contain at least 6 characters.', ar: 'يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل.' },
  'Impossible de créer le compte.': { en: 'Unable to create account.', ar: 'تعذر إنشاء الحساب.' },
  'L’employé se connectera uniquement avec son code.': { en: 'The employee will sign in using their code only.', ar: 'سيسجل الموظف الدخول باستخدام رمزه فقط.' },
  'Le responsable se connectera avec son email et son mot de passe.': { en: 'The manager will sign in with email and password.', ar: 'سيسجل المسؤول الدخول بالبريد الإلكتروني وكلمة المرور.' },
  'Minimum 6 caractères': { en: 'Minimum 6 characters', ar: '6 أحرف على الأقل' },
  'Nom et établissement obligatoires.': { en: 'Name and establishment are required.', ar: 'الاسم والمؤسسة مطلوبان.' },
  'Email du responsable obligatoire.': { en: 'Manager email is required.', ar: 'بريد المسؤول الإلكتروني مطلوب.' },
  'Le code employé doit contenir entre 4 et 12 caractères.': { en: 'Employee code must contain 4 to 12 characters.', ar: 'يجب أن يحتوي رمز الموظف على 4 إلى 12 حرفاً.' },
  'Impossible de modifier le compte.': { en: 'Unable to edit account.', ar: 'تعذر تعديل الحساب.' },
  'Compte modifié avec succès.': { en: 'Account updated successfully.', ar: 'تم تعديل الحساب بنجاح.' },
  'Les deux codes ne correspondent pas.': { en: 'The two codes do not match.', ar: 'الرمزان غير متطابقين.' },
  'Erreur inconnue': { en: 'Unknown error', ar: 'خطأ غير معروف' },
  'Aucun établissement': { en: 'No establishment', ar: 'لا توجد مؤسسة' },
  'Erreur analyse IA:': { en: 'AI analysis error:', ar: 'خطأ تحليل الذكاء الاصطناعي:' },
  'Impossible de lancer l’analyse des avis.': { en: 'Unable to start review analysis.', ar: 'تعذر بدء تحليل التقييمات.' },
  'La réponse de l’IA est invalide.': { en: 'The AI response is invalid.', ar: 'استجابة الذكاء الاصطناعي غير صالحة.' },
  'Avis analysés': { en: 'Reviews analyzed', ar: 'التقييمات التي تم تحليلها' },
  'Avis négatifs / moyens': { en: 'Negative / average reviews', ar: 'التقييمات السلبية / المتوسطة' },
  'Aucun point fort clairement identifié.': { en: 'No clear strength identified.', ar: 'لم يتم تحديد نقطة قوة واضحة.' },
  'Points à améliorer': { en: 'Areas to improve', ar: 'نقاط تحتاج إلى تحسين' },
  'Aucun point faible clairement identifié.': { en: 'No clear weakness identified.', ar: 'لم يتم تحديد نقطة ضعف واضحة.' },
  'Nouveau': { en: 'New', ar: 'جديد' },
  'Traité': { en: 'Processed', ar: 'تمت المعالجة' },
  'NÉGATIF': { en: 'NEGATIVE', ar: 'سلبي' },
  'CA fidélité': { en: 'Loyalty revenue', ar: 'إيرادات الولاء' },
  'Points distribués': { en: 'Points distributed', ar: 'النقاط الموزعة' },
  'Événements': { en: 'Events', ar: 'الأحداث' },
  'Provider et modèle sont obligatoires.': { en: 'Provider and model are required.', ar: 'مزود الخدمة والنموذج مطلوبان.' },
  'La température doit être entre 0 et 2.': { en: 'Temperature must be between 0 and 2.', ar: 'يجب أن تكون درجة الحرارة بين 0 و2.' },
  'Configuration IA enregistrée.': { en: 'AI configuration saved.', ar: 'تم حفظ إعدادات الذكاء الاصطناعي.' },
  'Veuillez saisir le prompt de génération des promotions.': { en: 'Please enter the promotion generation prompt.', ar: 'يرجى إدخال طلب إنشاء العروض.' },
  'Enregistrer le prompt promotions': { en: 'Save promotion prompt', ar: 'حفظ طلب العروض' },
  'Nouveau type': { en: 'New type', ar: 'نوع جديد' },
  'Modifier le type IA': { en: 'Edit AI type', ar: 'تعديل نوع الذكاء الاصطناعي' },
  'Créer un type IA': { en: 'Create AI type', ar: 'إنشاء نوع ذكاء اصطناعي' },
  'Rapport de performance': { en: 'Performance report', ar: 'تقرير الأداء' },
  'Rapport réputation & avis': { en: 'Reputation & reviews report', ar: 'تقرير السمعة والتقييمات' },
  'Rapport fidélité': { en: 'Loyalty report', ar: 'تقرير الولاء' },
  'Rapport équipe': { en: 'Team report', ar: 'تقرير الفريق' },
  'Aucun commentaire': { en: 'No comment', ar: 'لا يوجد تعليق' },
  'Voici ce qui se passe dans vos établissements.': { en: 'Here is what is happening in your establishments.', ar: 'إليك ما يحدث في مؤسساتك.' },
  'Aucun abonnement': { en: 'No subscription', ar: 'لا يوجد اشتراك' },
  'Période d’essai': { en: 'Trial period', ar: 'الفترة التجريبية' },
  'Aucun pack n’est actuellement attribué à cet établissement.': { en: 'No plan is currently assigned to this establishment.', ar: 'لا توجد خطة مخصصة حالياً لهذه المؤسسة.' },
  'Avis, réponses et suivi': { en: 'Reviews, replies and tracking', ar: 'التقييمات والردود والمتابعة' },
  'Comprendre les retours clients': { en: 'Understand customer feedback', ar: 'فهم ملاحظات العملاء' },
  'Clients, points et récompenses': { en: 'Customers, points and rewards', ar: 'العملاء والنقاط والمكافآت' },
  'Responsables et employés': { en: 'Managers and employees', ar: 'المسؤولون والموظفون' },
  'Catégories, plats et tarifs': { en: 'Categories, dishes and prices', ar: 'الفئات والأطباق والأسعار' },
  'Accès Wi-Fi de l’établissement': { en: 'Establishment Wi-Fi access', ar: 'الوصول إلى Wi-Fi المؤسسة' },
  'Règles, points et récompenses': { en: 'Rules, points and rewards', ar: 'القواعد والنقاط والمكافآت' },
  'Accéder aux supports clients': { en: 'Access customer materials', ar: 'الوصول إلى مواد العملاء' },
  'Depuis le début': { en: 'Since the beginning', ar: 'منذ البداية' },
  'Sur 5 étoiles': { en: 'Out of 5 stars', ar: 'من أصل 5 نجوم' },
  'Pas encore de données': { en: 'No data yet', ar: 'لا توجد بيانات بعد' },
  'Retours négatifs': { en: 'Negative feedback', ar: 'ملاحظات سلبية' },
  'Notes de 1 à 3 étoiles': { en: 'Ratings from 1 to 3 stars', ar: 'تقييمات من 1 إلى 3 نجوم' },
  'À traiter': { en: 'To process', ar: 'قيد المعالجة' },
  'Sur les 7 derniers jours': { en: 'Over the last 7 days', ar: 'خلال آخر 7 أيام' },
  'Solde total des clients': { en: 'Total customer balance', ar: 'إجمالي رصيد العملاء' },
  'Visites enregistrées': { en: 'Recorded visits', ar: 'الزيارات المسجلة' },
  'Total des visites fidélité': { en: 'Total loyalty visits', ar: 'إجمالي زيارات الولاء' },
  'Négatifs': { en: 'Negative', ar: 'سلبي' },
  'Avis positif sans commentaire': { en: 'Positive review without comment', ar: 'تقييم إيجابي بدون تعليق' },
  'Votre établissement': { en: 'Your establishment', ar: 'مؤسستك' },
  'Votre réseau': { en: 'Your network', ar: 'شبكتك' },
  'Impossible d’envoyer votre avis.': { en: 'Unable to submit your review.', ar: 'تعذر إرسال تقييمك.' },
  'Trop de tentatives. Veuillez réessayer plus tard.': { en: 'Too many attempts. Please try again later.', ar: 'محاولات كثيرة جداً. يرجى المحاولة لاحقاً.' },
  'Impossible d’envoyer votre message. Veuillez réessayer.': { en: 'Unable to send your message. Please try again.', ar: 'تعذر إرسال رسالتك. يرجى المحاولة مرة أخرى.' },
  'Veuillez saisir votre prénom.': { en: 'Please enter your first name.', ar: 'يرجى إدخال الاسم الأول.' },
  'Veuillez saisir votre nom.': { en: 'Please enter your last name.', ar: 'يرجى إدخال اسم العائلة.' },
  'Veuillez saisir votre numéro de téléphone.': { en: 'Please enter your phone number.', ar: 'يرجى إدخال رقم هاتفك.' },
  'Ce numéro est déjà inscrit au programme fidélité.': { en: 'This number is already enrolled in the loyalty program.', ar: 'هذا الرقم مسجل بالفعل في برنامج الولاء.' },
  'Impossible de créer votre carte fidélité.': { en: 'Unable to create your loyalty card.', ar: 'تعذر إنشاء بطاقة الولاء الخاصة بك.' },
  'Rejoindre notre programme fidélité': { en: 'Join our loyalty program', ar: 'انضم إلى برنامج الولاء لدينا' },
  'Cumulez des points et profitez d’avantages exclusifs': { en: 'Earn points and enjoy exclusive benefits', ar: 'اجمع النقاط واستفد من مزايا حصرية' },
  'Laisser un avis Google': { en: 'Leave a Google review', ar: 'اترك تقييماً على Google' },
  'Votre avis compte beaucoup pour nous': { en: 'Your review means a lot to us', ar: 'رأيك مهم جداً بالنسبة لنا' },
  'Découvrez nos plats et boissons': { en: 'Discover our dishes and drinks', ar: 'اكتشف أطباقنا ومشروباتنا' },
  'Que pouvons-nous améliorer ?': { en: 'What can we improve?', ar: 'ماذا يمكننا تحسينه؟' },
  'Voici ma carte fidélité.': { en: 'Here is my loyalty card.', ar: 'هذه بطاقة الولاء الخاصة بي.' },
  'Créez gratuitement votre carte fidélité.': { en: 'Create your loyalty card for free.', ar: 'أنشئ بطاقة الولاء الخاصة بك مجاناً.' },
  'À chaque achat ou visite, vous accumulez des points.': { en: 'Earn points with every purchase or visit.', ar: 'اكسب النقاط مع كل عملية شراء أو زيارة.' },
  'Soyez récompensé': { en: 'Get rewarded', ar: 'احصل على المكافآت' },
  'Utilisez vos points pour profiter de vos avantages.': { en: 'Use your points to enjoy your benefits.', ar: 'استخدم نقاطك للاستفادة من مزاياك.' },
  'Numéro de téléphone': { en: 'Phone number', ar: 'رقم الهاتف' },
  'Création de votre carte...': { en: 'Creating your card...', ar: 'جارٍ إنشاء بطاقتك...' },
  'Créer ma carte fidélité': { en: 'Create my loyalty card', ar: 'إنشاء بطاقة الولاء الخاصة بي' },
  'Menu bientôt disponible': { en: 'Menu coming soon', ar: 'القائمة ستكون متاحة قريباً' },
  'Le contenu apparaîtra ici dès qu’il sera ajouté.': { en: 'Content will appear here once it is added.', ar: 'سيظهر المحتوى هنا بمجرد إضافته.' },
  'Copié': { en: 'Copied', ar: 'تم النسخ' },
  'Aucun mot de passe': { en: 'No password', ar: 'لا توجد كلمة مرور' },
  'Lien scanner invalide ou expiré.': { en: 'Scanner link is invalid or expired.', ar: 'رابط الماسح غير صالح أو منتهي الصلاحية.' },
  'Ce lien scanner appartient à un autre établissement.': { en: 'This scanner link belongs to another establishment.', ar: 'رابط الماسح هذا تابع لمؤسسة أخرى.' },
  'Veuillez saisir votre code employé.': { en: 'Please enter your employee code.', ar: 'يرجى إدخال رمز الموظف.' },
  'Code employé incorrect.': { en: 'Incorrect employee code.', ar: 'رمز الموظف غير صحيح.' },
  'Impossible de se connecter pour le moment.': { en: 'Unable to sign in right now.', ar: 'تعذر تسجيل الدخول حالياً.' },
  'Veuillez saisir le prénom.': { en: 'Please enter the first name.', ar: 'يرجى إدخال الاسم الأول.' },
  'Veuillez saisir le numéro de téléphone.': { en: 'Please enter the phone number.', ar: 'يرجى إدخال رقم الهاتف.' },
  'Un client avec ce numéro existe déjà dans cet établissement.': { en: 'A customer with this number already exists in this establishment.', ar: 'يوجد عميل بهذا الرقم بالفعل في هذه المؤسسة.' },
  'Prénom, nom et téléphone sont obligatoires.': { en: 'First name, last name and phone are required.', ar: 'الاسم الأول واسم العائلة والهاتف مطلوبة.' },
  'Informations du client mises à jour.': { en: 'Customer information updated.', ar: 'تم تحديث معلومات العميل.' },
  'Autorisez les fenêtres pop-up pour imprimer la carte.': { en: 'Allow pop-ups to print the card.', ar: 'اسمح بالنوافذ المنبثقة لطباعة البطاقة.' },
  'Cet établissement utilise un programme à tampons. Les points ne peuvent pas être ajoutés.': { en: 'This establishment uses a stamp program. Points cannot be added.', ar: 'تستخدم هذه المؤسسة برنامج أختام. لا يمكن إضافة النقاط.' },
  'Le programme de fidélité est désactivé pour cet établissement.': { en: 'The loyalty program is disabled for this establishment.', ar: 'برنامج الولاء معطل لهذه المؤسسة.' },
  'Veuillez saisir un montant valide.': { en: 'Please enter a valid amount.', ar: 'يرجى إدخال مبلغ صالح.' },
  'Le client ne possède pas assez de points.': { en: 'The customer does not have enough points.', ar: 'لا يملك العميل نقاطاً كافية.' },
  'Le numéro de facture est obligatoire.': { en: 'Invoice number is required.', ar: 'رقم الفاتورة مطلوب.' },
  'Veuillez saisir un montant de facture valide.': { en: 'Please enter a valid invoice amount.', ar: 'يرجى إدخال مبلغ فاتورة صالح.' },
  'Carte inconnue. Vérifiez le QR ou utilisez le code / téléphone.': { en: 'Unknown card. Check the QR code or use the code / phone.', ar: 'بطاقة غير معروفة. تحقق من رمز QR أو استخدم الرمز / الهاتف.' },
  'Cette carte appartient à un autre établissement.': { en: 'This card belongs to another establishment.', ar: 'هذه البطاقة تابعة لمؤسسة أخرى.' },
  'Code de connexion': { en: 'Login code', ar: 'رمز الدخول' },
  'Accéder à mon espace': { en: 'Access my workspace', ar: 'الوصول إلى مساحتي' },
  'N° fidélité, téléphone, prénom ou nom...': { en: 'Loyalty no., phone, first or last name...', ar: 'رقم الولاء، الهاتف، الاسم الأول أو العائلة...' },
  'Désactivé': { en: 'Disabled', ar: 'معطل' },
  'Nouveau client': { en: 'New customer', ar: 'عميل جديد' },
  'Date de naissance (optionnel)': { en: 'Date of birth (optional)', ar: 'تاريخ الميلاد (اختياري)' },
  'Créer le client': { en: 'Create customer', ar: 'إنشاء العميل' },
  'Modifier le client': { en: 'Edit customer', ar: 'تعديل العميل' },
  'Date de naissance': { en: 'Date of birth', ar: 'تاريخ الميلاد' },
  'Carte de fidélité': { en: 'Loyalty card', ar: 'بطاقة الولاء' },
  'Cadeau fidélité': { en: 'Loyalty gift', ar: 'هدية الولاء' },
  'Lien de la carte copié.': { en: 'Card link copied.', ar: 'تم نسخ رابط البطاقة.' },
  'Ajouter des points': { en: 'Add points', ar: 'إضافة نقاط' },
  'Numéro de facture (optionnel)': { en: 'Invoice number (optional)', ar: 'رقم الفاتورة (اختياري)' },
  'Valider les points': { en: 'Confirm points', ar: 'تأكيد النقاط' },
  'Utiliser une récompense': { en: 'Redeem a reward', ar: 'استخدام مكافأة' },
  'Numéro de facture': { en: 'Invoice number', ar: 'رقم الفاتورة' },
  'Espèces': { en: 'Cash', ar: 'نقداً' },
  'Valider la récompense': { en: 'Redeem reward', ar: 'تأكيد استخدام المكافأة' },

  'Accueil': { en: 'Home', ar: 'الرئيسية' },
  'Vue générale': { en: 'Overview', ar: 'نظرة عامة' },
  'Espace administrateur': { en: 'Administrator workspace', ar: 'مساحة المشرف' },
  'Espace responsable': { en: 'Manager workspace', ar: 'مساحة المسؤول' },
  'Espace établissement': { en: 'Establishment workspace', ar: 'مساحة المؤسسة' },
  'Gérer': { en: 'Manage', ar: 'إدارة' },
  'Gestion': { en: 'Management', ar: 'الإدارة' },
  'Profil': { en: 'Profile', ar: 'الملف الشخصي' },
  'Informations': { en: 'Information', ar: 'المعلومات' },
  'Description': { en: 'Description', ar: 'الوصف' },
  'Nom de l’établissement': { en: 'Establishment name', ar: 'اسم المؤسسة' },
  'Nom de l’établissement *': { en: 'Establishment name *', ar: 'اسم المؤسسة *' },
  'Créer un établissement': { en: 'Create establishment', ar: 'إنشاء مؤسسة' },
  'Nouvel établissement': { en: 'New establishment', ar: 'مؤسسة جديدة' },
  'Aucun établissement': { en: 'No establishments', ar: 'لا توجد مؤسسات' },
  'Sélectionnez ou créez un établissement avant d’utiliser cette fonctionnalité.': { en: 'Select or create an establishment before using this feature.', ar: 'اختر مؤسسة أو أنشئ مؤسسة قبل استخدام هذه الميزة.' },
  'Crée d’abord ton établissement pour gérer ses promotions.': { en: 'Create your establishment first to manage its promotions.', ar: 'أنشئ مؤسستك أولاً لإدارة عروضها.' },
  'Avis': { en: 'Reviews', ar: 'التقييمات' },
  'Avis Google': { en: 'Google reviews', ar: 'تقييمات Google' },
  'Réputation': { en: 'Reputation', ar: 'السمعة' },
  'Répondre aux avis': { en: 'Reply to reviews', ar: 'الرد على التقييمات' },
  'Nouvel avis client': { en: 'New customer review', ar: 'تقييم عميل جديد' },
  'Note moyenne': { en: 'Average rating', ar: 'متوسط التقييم' },
  'Analyse': { en: 'Analysis', ar: 'التحليل' },
  'Analyses': { en: 'Analysis', ar: 'التحليلات' },
  'Analyse des avis': { en: 'Review analysis', ar: 'تحليل التقييمات' },
  'Statut': { en: 'Status', ar: 'الحالة' },
  'En attente': { en: 'Pending', ar: 'قيد الانتظار' },
  'Traité': { en: 'Processed', ar: 'تمت المعالجة' },
  'Approuvé': { en: 'Approved', ar: 'تمت الموافقة' },
  'Refusé': { en: 'Rejected', ar: 'مرفوض' },
  'Erreur': { en: 'Error', ar: 'خطأ' },
  'Succès': { en: 'Success', ar: 'نجاح' },
  'Avertissement': { en: 'Warning', ar: 'تحذير' },
  'Impossible': { en: 'Unable', ar: 'تعذر' },
  'Impossible de charger les données.': { en: 'Unable to load data.', ar: 'تعذر تحميل البيانات.' },
  'Une erreur est survenue.': { en: 'An error occurred.', ar: 'حدث خطأ.' },
  'Enregistrer les modifications': { en: 'Save changes', ar: 'حفظ التغييرات' },
  'Enregistrer': { en: 'Save', ar: 'حفظ' },
  'Enregistré': { en: 'Saved', ar: 'تم الحفظ' },
  'Enregistrée': { en: 'Saved', ar: 'تم الحفظ' },
  'Créer': { en: 'Create', ar: 'إنشاء' },
  'Créer maintenant': { en: 'Create now', ar: 'إنشاء الآن' },
  'Ajouter': { en: 'Add', ar: 'إضافة' },
  'Ajouter un client': { en: 'Add customer', ar: 'إضافة عميل' },
  'Modifier': { en: 'Edit', ar: 'تعديل' },
  'Modifier l’établissement': { en: 'Edit establishment', ar: 'تعديل المؤسسة' },
  'Supprimer': { en: 'Delete', ar: 'حذف' },
  'Confirmer': { en: 'Confirm', ar: 'تأكيد' },
  'Fermer': { en: 'Close', ar: 'إغلاق' },
  'Annuler': { en: 'Cancel', ar: 'إلغاء' },
  'Retour': { en: 'Back', ar: 'رجوع' },
  'Continuer': { en: 'Continue', ar: 'متابعة' },
  'Valider': { en: 'Confirm', ar: 'تأكيد' },
  'Rechercher': { en: 'Search', ar: 'بحث' },
  'Filtrer': { en: 'Filter', ar: 'تصفية' },
  'Réinitialiser': { en: 'Reset', ar: 'إعادة تعيين' },
  'Actualiser': { en: 'Refresh', ar: 'تحديث' },
  'Rafraîchir': { en: 'Refresh', ar: 'تحديث' },
  'Exporter': { en: 'Export', ar: 'تصدير' },
  'Télécharger': { en: 'Download', ar: 'تنزيل' },
  'Imprimer': { en: 'Print', ar: 'طباعة' },
  'Copier le lien': { en: 'Copy link', ar: 'نسخ الرابط' },
  'Lien copié': { en: 'Link copied', ar: 'تم نسخ الرابط' },
  'Ouvrir': { en: 'Open', ar: 'فتح' },
  'Voir': { en: 'View', ar: 'عرض' },
  'Voir tout': { en: 'View all', ar: 'عرض الكل' },
  'Voir plus': { en: 'View more', ar: 'عرض المزيد' },
  'Détails': { en: 'Details', ar: 'التفاصيل' },
  'Actions': { en: 'Actions', ar: 'الإجراءات' },
  'Date': { en: 'Date', ar: 'التاريخ' },
  'Aujourd’hui': { en: 'Today', ar: 'اليوم' },
  'Aujourd’hui': { en: 'Today', ar: 'اليوم' },
  'Hier': { en: 'Yesterday', ar: 'أمس' },
  'Cette semaine': { en: 'This week', ar: 'هذا الأسبوع' },
  'Ce mois-ci': { en: 'This month', ar: 'هذا الشهر' },
  'Mois': { en: 'Month', ar: 'الشهر' },
  'Semaine': { en: 'Week', ar: 'الأسبوع' },
  'Année': { en: 'Year', ar: 'السنة' },
  '7 derniers jours': { en: 'Last 7 days', ar: 'آخر 7 أيام' },
  '30 derniers jours': { en: 'Last 30 days', ar: 'آخر 30 days' },
  '90 derniers jours': { en: 'Last 90 days', ar: 'آخر 90 يوماً' },
  'Aucun résultat': { en: 'No results', ar: 'لا توجد نتائج' },
  'Aucune donnée': { en: 'No data', ar: 'لا توجد بيانات' },
  'Aucun avis': { en: 'No reviews', ar: 'لا توجد تقييمات' },
  'Aucun client': { en: 'No customers', ar: 'لا يوجد عملاء' },
  'Aucune promotion': { en: 'No promotions', ar: 'لا توجد عروض' },
  'Aucune promotion publiée': { en: 'No published promotions', ar: 'لا توجد عروض منشورة' },
  'Chargement': { en: 'Loading', ar: 'جارٍ التحميل' },
  'Chargement…': { en: 'Loading…', ar: 'جارٍ التحميل…' },
  'Chargement...': { en: 'Loading...', ar: 'جارٍ التحميل...' },
  'En cours': { en: 'In progress', ar: 'قيد التنفيذ' },
  'Actif': { en: 'Active', ar: 'نشط' },
  'Active': { en: 'Active', ar: 'نشط' },
  'Inactif': { en: 'Inactive', ar: 'غير نشط' },
  'Activé': { en: 'Enabled', ar: 'مفعّل' },
  'Désactivé': { en: 'Disabled', ar: 'معطّل' },
  'Oui': { en: 'Yes', ar: 'نعم' },
  'Non': { en: 'No', ar: 'لا' },
  'Nom': { en: 'Name', ar: 'الاسم' },
  'Prénom': { en: 'First name', ar: 'الاسم الأول' },
  'Nom de famille': { en: 'Last name', ar: 'اسم العائلة' },
  'Téléphone': { en: 'Phone', ar: 'الهاتف' },
  'Adresse': { en: 'Address', ar: 'العنوان' },
  'Email': { en: 'Email', ar: 'البريد الإلكتروني' },
  'Mot de passe': { en: 'Password', ar: 'كلمة المرور' },
  'Code': { en: 'Code', ar: 'الرمز' },
  'Prix': { en: 'Price', ar: 'السعر' },
  'Prix normal': { en: 'Regular price', ar: 'السعر العادي' },
  'Prix promo': { en: 'Promotional price', ar: 'السعر الترويجي' },
  'Description': { en: 'Description', ar: 'الوصف' },
  'Catégorie': { en: 'Category', ar: 'الفئة' },
  'Catégories': { en: 'Categories', ar: 'الفئات' },
  'Produit': { en: 'Product', ar: 'المنتج' },
  'Produits': { en: 'Products', ar: 'المنتجات' },
  'Article': { en: 'Item', ar: 'العنصر' },
  'Articles': { en: 'Items', ar: 'العناصر' },
  'Menu digital': { en: 'Digital menu', ar: 'القائمة الرقمية' },
  'Concevoir le menu': { en: 'Design menu', ar: 'تصميم القائمة' },
  'Aperçu': { en: 'Overview', ar: 'نظرة عامة' },
  'Publier': { en: 'Publish', ar: 'نشر' },
  'Publication': { en: 'Publishing', ar: 'النشر' },
  'Publié': { en: 'Published', ar: 'منشور' },
  'Promotion': { en: 'Promotion', ar: 'عرض ترويجي' },
  'Promotions': { en: 'Promotions', ar: 'العروض' },
  'Nouvelle promotion': { en: 'New promotion', ar: 'عرض ترويجي جديد' },
  'Tes promotions': { en: 'Your promotions', ar: 'عروضك' },
  'Générer et publier avec l’IA': { en: 'Generate and publish with AI', ar: 'إنشاء ونشر بالذكاء الاصطناعي' },
  'Génération du visuel…': { en: 'Generating visual…', ar: 'جارٍ إنشاء التصميم…' },
  'Fidélité': { en: 'Loyalty', ar: 'الولاء' },
  'Programme de fidélité': { en: 'Loyalty program', ar: 'برنامج الولاء' },
  'Clients fidélisés': { en: 'Loyal customers', ar: 'العملاء المخلصون' },
  'Clients': { en: 'Customers', ar: 'العملاء' },
  'Membres': { en: 'Members', ar: 'الأعضاء' },
  'Récompenses': { en: 'Rewards', ar: 'المكافآت' },
  'Récompense': { en: 'Reward', ar: 'مكافأة' },
  'Points': { en: 'Points', ar: 'النقاط' },
  'Visites': { en: 'Visits', ar: 'الزيارات' },
  'Réductions': { en: 'Discounts', ar: 'الخصومات' },
  'Avantages': { en: 'Benefits', ar: 'المزايا' },
  'Campagnes': { en: 'Campaigns', ar: 'الحملات' },
  'Scanner fidélité': { en: 'Loyalty scanner', ar: 'ماسح الولاء' },
  'Nouveau client': { en: 'New customer', ar: 'عميل جديد' },
  'Nouveau client fidélité': { en: 'New loyalty customer', ar: 'عميل ولاء جديد' },
  'Points fidélité ajoutés': { en: 'Loyalty points added', ar: 'تمت إضافة نقاط الولاء' },
  'Récompense utilisée': { en: 'Reward redeemed', ar: 'تم استخدام المكافأة' },
  'Opération fidélité': { en: 'Loyalty activity', ar: 'عملية ولاء' },
  'Enregistrer ma carte sur mon téléphone': { en: 'Save my card on my phone', ar: 'حفظ بطاقتي على هاتفي' },
  'Ajoutez-la à votre écran d’accueil ou partagez votre carte.': { en: 'Add it to your home screen or share your card.', ar: 'أضفها إلى شاشتك الرئيسية أو شارك بطاقتك.' },
  'Ma carte fidélité': { en: 'My loyalty card', ar: 'بطاقة الولاء الخاصة بي' },
  'Carte indisponible': { en: 'Card unavailable', ar: 'البطاقة غير متاحة' },
  'Carte de fidélité introuvable.': { en: 'Loyalty card not found.', ar: 'لم يتم العثور على بطاقة الولاء.' },
  'Appeler': { en: 'Call', ar: 'اتصال' },
  'WhatsApp': { en: 'WhatsApp', ar: 'واتساب' },
  'Sécurité': { en: 'Security', ar: 'الأمان' },
  'Paramètres': { en: 'Settings', ar: 'الإعدادات' },
  'Notifications': { en: 'Notifications', ar: 'الإشعارات' },
  'Système': { en: 'System', ar: 'النظام' },
  'Rapports': { en: 'Reports', ar: 'التقارير' },
  'Facturation': { en: 'Billing', ar: 'الفوترة' },
  'Abonnement': { en: 'Subscription', ar: 'الاشتراك' },
  'Abonnements': { en: 'Subscriptions', ar: 'الاشتراكات' },
  'Essai': { en: 'Trial', ar: 'تجربة' },
  'Actif ·': { en: 'Active ·', ar: 'نشط ·' },
  'Se déconnecter': { en: 'Sign out', ar: 'تسجيل الخروج' },
  'Bienvenue': { en: 'Welcome', ar: 'مرحباً' },
  'Bon retour 👋': { en: 'Welcome back 👋', ar: 'مرحباً بعودتك 👋' },
  'Aide': { en: 'Help', ar: 'المساعدة' },
  'En savoir plus': { en: 'Learn more', ar: 'معرفة المزيد' },
  'L’expérience client, c’est un atout.': { en: 'Customer experience is an asset.', ar: 'تجربة العميل هي ميزة.' },
  'Crée une promotion avec l’IA': { en: 'Create a promotion with AI', ar: 'أنشئ عرضاً ترويجياً بالذكاء الاصطناعي' },
  'Le visuel est toujours généré par l’IA.': { en: 'The visual is always generated by AI.', ar: 'يتم إنشاء التصميم دائماً بواسطة الذكاء الاصطناعي.' },
};
Object.assign(uiTranslations, expandedUiTranslations);

function sourceUiText(value: string) {
  const clean = value.trim();
  if (uiTranslations[clean]) return clean;
  for (const [source, translation] of Object.entries(uiTranslations)) {
    if (translation.en === clean || translation.ar === clean) return source;
  }
  return value;
}

function translateUiText(value: string, language: Language) {
  const source = sourceUiText(value);
  const clean = source.trim();
  const translation = uiTranslations[clean];
  if (!translation || language === 'fr') return value.replace(value.trim(), clean);
  return value.replace(value.trim(), translation[language]);
}

const translations = {
  fr: {
    language: 'Français',
    welcome: 'Bon retour 👋',
    loginTitle: 'Connectez-vous à votre espace',
    loginSubtitle: 'Accédez à toutes vos fonctionnalités et continuez à faire grandir votre établissement.',
    admin: 'Administrateur',
    responsible: 'Responsable',
    adminDesc: 'Gestion globale',
    responsibleDesc: 'Gestion de l’établissement',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    emailPlaceholder: 'votre@email.com',
    passwordPlaceholder: 'Votre mot de passe',
    forgot: 'Mot de passe oublié ?',
    login: 'Se connecter',
    changeSpace: 'Changer d’espace',
    selectSpace: 'Sélectionnez votre espace pour continuer.',
    createAccount: 'Créer un compte',
    back: 'Retour',
    services: {
      reviews: 'Avis & Réputation',
      reviewsDesc: 'Collectez, analysez et gérez vos avis sur Google et les principales plateformes.',
      loyalty: 'Fidélité',
      loyaltyDesc: 'Récompensez vos clients et donnez-leur envie de revenir.',
      experience: 'Expérience client',
      experienceDesc: 'Mesurez la satisfaction et améliorez chaque étape du parcours.',
      performance: 'Performance',
      performanceDesc: 'Suivez vos données, identifiez vos opportunités et prenez de meilleures décisions.',
    },
    hero: 'Transformez chaque client en',
    heroAccent: 'client fidèle.',
    heroDesc: 'Tap Marrakech vous aide à gérer vos avis, fidéliser vos clients et offrir une expérience exceptionnelle, simplement.',
    allInOne: 'Plateforme tout-en-un',
    establishments: 'établissements',
    reviewsManaged: 'avis gérés',
    recurring: 'clients récurrents',
    platformAccess: 'Accès plateforme',
    establishmentSpace: 'Espace établissement',
    secured: 'Sécurisé',
    simple: 'Simple',
    experienceShort: 'Expérience client',
  },
  en: {
    language: 'English',
    welcome: 'Welcome back 👋',
    loginTitle: 'Sign in to your workspace',
    loginSubtitle: 'Access all your features and keep growing your establishment.',
    admin: 'Administrator',
    responsible: 'Manager',
    adminDesc: 'Global management',
    responsibleDesc: 'Establishment management',
    email: 'Email address',
    password: 'Password',
    emailPlaceholder: 'you@email.com',
    passwordPlaceholder: 'Your password',
    forgot: 'Forgot password?',
    login: 'Sign in',
    changeSpace: 'Change workspace',
    selectSpace: 'Select your workspace to continue.',
    createAccount: 'Create an account',
    back: 'Back',
    services: {
      reviews: 'Reviews & Reputation',
      reviewsDesc: 'Collect, analyze and manage your reviews on Google and major platforms.',
      loyalty: 'Loyalty',
      loyaltyDesc: 'Reward your customers and give them a reason to come back.',
      experience: 'Customer experience',
      experienceDesc: 'Measure satisfaction and improve every step of the journey.',
      performance: 'Performance',
      performanceDesc: 'Track your data, identify opportunities and make better decisions.',
    },
    hero: 'Turn every customer into a',
    heroAccent: 'loyal customer.',
    heroDesc: 'Tap Marrakech helps you manage reviews, build loyalty and deliver an exceptional customer experience, simply.',
    allInOne: 'All-in-one platform',
    establishments: 'establishments',
    reviewsManaged: 'reviews managed',
    recurring: 'returning customers',
    platformAccess: 'Platform access',
    establishmentSpace: 'Establishment workspace',
    secured: 'Secure',
    simple: 'Simple',
    experienceShort: 'Customer experience',
  },
  ar: {
    language: 'العربية',
    welcome: 'مرحباً بعودتك 👋',
    loginTitle: 'سجّل الدخول إلى مساحتك',
    loginSubtitle: 'الوصول إلى جميع الميزات ومواصلة تطوير مؤسستك.',
    admin: 'المشرف',
    responsible: 'المسؤول',
    adminDesc: 'إدارة شاملة',
    responsibleDesc: 'إدارة المؤسسة',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    emailPlaceholder: 'you@email.com',
    passwordPlaceholder: 'كلمة المرور الخاصة بك',
    forgot: 'هل نسيت كلمة المرور؟',
    login: 'تسجيل الدخول',
    changeSpace: 'تغيير المساحة',
    selectSpace: 'اختر مساحتك للمتابعة.',
    createAccount: 'إنشاء حساب',
    back: 'رجوع',
    services: {
      reviews: 'التقييمات والسمعة',
      reviewsDesc: 'اجمع وحلل وأدر تقييماتك على Google والمنصات الرئيسية.',
      loyalty: 'الولاء',
      loyaltyDesc: 'كافئ عملاءك وشجعهم على العودة.',
      experience: 'تجربة العميل',
      experienceDesc: 'قس رضا العملاء وحسّن كل مرحلة من رحلتهم.',
      performance: 'الأداء',
      performanceDesc: 'تابع بياناتك وحدد فرصك واتخذ قرارات أفضل.',
    },
    hero: 'حوّل كل عميل إلى',
    heroAccent: 'عميل وفيّ.',
    heroDesc: 'تساعدك Tap Marrakech على إدارة تقييماتك وتعزيز ولاء عملائك وتقديم تجربة استثنائية ببساطة.',
    allInOne: 'منصة متكاملة',
    establishments: 'مؤسسة',
    reviewsManaged: 'تقييم مُدار',
    recurring: 'عملاء عائدون',
    platformAccess: 'الوصول إلى المنصة',
    establishmentSpace: 'مساحة المؤسسة',
    secured: 'آمن',
    simple: 'بسيط',
    experienceShort: 'تجربة العميل',
  },
} as const;

type Translation = typeof translations[Language];

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: Translation;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = window.localStorage.getItem('tapmarrakech:language');
    return saved === 'en' || saved === 'ar' ? saved : 'fr';
  });

  const setLanguage = (next: Language) => {
    setLanguageState(next);
    window.localStorage.setItem('tapmarrakech:language', next);
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  useEffect(() => {
    const translatableAttributes = ['placeholder', 'title', 'aria-label', 'alt'];

    const translateNode = (node: Text) => {
      const current = node.nodeValue ?? '';
      if (!current.trim()) return;
      if (!originalTextNodes.has(node)) originalTextNodes.set(node, current);
      const source = originalTextNodes.get(node) ?? current;
      const translated = translateUiText(source, language);
      if (node.nodeValue !== translated) node.nodeValue = translated;
    };

    const translateElement = (element: Element) => {
      if (element.tagName === 'SCRIPT' || element.tagName === 'STYLE') return;
      const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
      let current: Node | null;
      while ((current = walker.nextNode())) translateNode(current as Text);
      for (const attribute of translatableAttributes) {
        const value = element.getAttribute(attribute);
        if (!value?.trim()) continue;
        const key = 'tapmarrakech:i18n:' + attribute;
        const original = element.getAttribute(key) ?? value;
        if (!element.hasAttribute(key)) element.setAttribute(key, original);
        const translated = translateUiText(original, language);
        if (value !== translated && value !== original) element.setAttribute(attribute, translated);
        else if (value === original && translated !== original) element.setAttribute(attribute, translated);
      }
    };

    translateElement(document.body);

    const observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        if (mutation.type === 'characterData') translateNode(mutation.target as Text);
        mutation.addedNodes.forEach((node) => {
          if (node.nodeType === Node.TEXT_NODE) translateNode(node as Text);
          else if (node.nodeType === Node.ELEMENT_NODE) translateElement(node as Element);
        });
      }
    });

    observer.observe(document.body, { childList: true, subtree: true, characterData: true });
    return () => observer.disconnect();
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: translations[language],
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
