-- KELYANI customer levels + raffle eligibility
create table if not exists public.loyalty_tiers (
 id uuid primary key default gen_random_uuid(), establishment_id uuid not null references public.establishments(id) on delete cascade,
 tier_key text not null check (tier_key in ('STANDARD','BRONZE','SILVER','GOLD','PLATINUM')), name text not null, sort_order integer not null,
 min_total_points integer not null default 0, min_rewards_redeemed integer not null default 0,
 qualification_mode text not null default 'OR' check (qualification_mode in ('OR','AND')),
 ticket_multiplier integer not null default 1 check(ticket_multiplier between 1 and 100), active boolean not null default true,
 unique(establishment_id,tier_key), unique(establishment_id,sort_order)
);
alter table public.loyalty_tiers enable row level security;
drop policy if exists loyalty_tiers_access on public.loyalty_tiers;
create policy loyalty_tiers_access on public.loyalty_tiers for all to authenticated using(public.is_tapmarrakech_admin() or public.user_has_establishment_access(establishment_id)) with check(public.is_tapmarrakech_admin() or public.is_establishment_responsible(establishment_id));
alter table public.loyalty_raffles add column if not exists minimum_tier_key text not null default 'STANDARD' check(minimum_tier_key in ('STANDARD','BRONZE','SILVER','GOLD','PLATINUM'));
alter table public.loyalty_raffles add column if not exists ticket_multiplier_mode text not null default 'TIER' check(ticket_multiplier_mode in ('TIER','ONE'));
alter table public.loyalty_raffles add column if not exists eligibility_snapshot_at timestamptz;

create or replace function public.ensure_default_loyalty_tiers(p_establishment_id uuid) returns void language plpgsql security definer set search_path=public as $$
begin
 if not(public.is_tapmarrakech_admin() or public.is_establishment_responsible(p_establishment_id)) then raise exception 'not_authorized'; end if;
 insert into public.loyalty_tiers(establishment_id,tier_key,name,sort_order,min_total_points,min_rewards_redeemed,qualification_mode,ticket_multiplier) values
 (p_establishment_id,'STANDARD','Standard',0,0,0,'OR',1),(p_establishment_id,'BRONZE','Bronze',1,250,1,'OR',2),(p_establishment_id,'SILVER','Silver',2,750,3,'OR',3),(p_establishment_id,'GOLD','Gold',3,1500,5,'OR',5),(p_establishment_id,'PLATINUM','Platinum',4,3000,8,'OR',10) on conflict(establishment_id,tier_key) do nothing;
end; $$;

create or replace function public.get_loyalty_customer_tier(p_customer_id uuid) returns table(tier_key text,tier_name text,sort_order integer,total_points integer,rewards_redeemed integer,ticket_multiplier integer,min_total_points integer,min_rewards_redeemed integer,qualification_mode text,next_tier_key text,next_tier_name text,next_points integer,next_rewards integer)
language sql stable security definer set search_path=public as $$
with c as(select lc.id,lc.establishment_id,coalesce(lc.total_points_earned,0) total_points,(select count(*)::int from public.loyalty_reward_claims rc where rc.customer_id=lc.id and rc.status='REDEEMED')+(select count(*)::int from public.loyalty_stamp_reward_claims sc where sc.customer_id=lc.id and sc.status='REDEEMED') rewards_redeemed from public.loyalty_customers lc where lc.id=p_customer_id),
q as(select t.*,c.total_points,c.rewards_redeemed from c join public.loyalty_tiers t on t.establishment_id=c.establishment_id and t.active where (t.qualification_mode='OR' and(c.total_points>=t.min_total_points or c.rewards_redeemed>=t.min_rewards_redeemed)) or(t.qualification_mode='AND' and c.total_points>=t.min_total_points and c.rewards_redeemed>=t.min_rewards_redeemed)),ct as(select * from q order by sort_order desc limit 1),n as(select t.* from public.loyalty_tiers t,ct where t.establishment_id=ct.establishment_id and t.active and t.sort_order>ct.sort_order order by t.sort_order limit 1)
select ct.tier_key,ct.name,ct.sort_order,ct.total_points,ct.rewards_redeemed,ct.ticket_multiplier,ct.min_total_points,ct.min_rewards_redeemed,ct.qualification_mode,n.tier_key,n.name,n.min_total_points,n.min_rewards_redeemed from ct left join n on true; $$;

create or replace function public.get_loyalty_tiers(p_establishment_id uuid) returns table(id uuid,tier_key text,name text,sort_order integer,min_total_points integer,min_rewards_redeemed integer,qualification_mode text,ticket_multiplier integer,active boolean)
language plpgsql security definer set search_path=public as $$ begin perform public.ensure_default_loyalty_tiers(p_establishment_id); return query select t.id,t.tier_key,t.name,t.sort_order,t.min_total_points,t.min_rewards_redeemed,t.qualification_mode,t.ticket_multiplier,t.active from public.loyalty_tiers t where t.establishment_id=p_establishment_id order by t.sort_order; end; $$;

create or replace function public.update_loyalty_tier(p_tier_id uuid,p_name text,p_min_points integer,p_min_rewards integer,p_mode text,p_ticket_multiplier integer,p_active boolean) returns void language plpgsql security definer set search_path=public as $$ declare eid uuid; begin select establishment_id into eid from public.loyalty_tiers where id=p_tier_id; if eid is null or not(public.is_tapmarrakech_admin() or public.is_establishment_responsible(eid)) then raise exception 'not_authorized'; end if; update public.loyalty_tiers set name=trim(p_name),min_total_points=p_min_points,min_rewards_redeemed=p_min_rewards,qualification_mode=p_mode,ticket_multiplier=p_ticket_multiplier,active=p_active where id=p_tier_id; end; $$;

drop function if exists public.get_loyalty_raffles(uuid);
create or replace function public.get_loyalty_raffles(p_establishment_id uuid) returns table(id uuid,title text,description text,prize_name text,prize_description text,starts_at timestamptz,draw_at timestamptz,winners_count integer,participation_mode text,reward_validity_mode text,reward_valid_from timestamptz,reward_valid_until timestamptz,reward_valid_days integer,reservation_required boolean,single_use boolean,non_cumulative boolean,status text,drawn_at timestamptz,participant_count bigint,winner_count bigint,minimum_tier_key text,ticket_multiplier_mode text)
language sql stable security definer set search_path=public as $$ select r.id,r.title,r.description,r.prize_name,r.prize_description,r.starts_at,r.draw_at,r.winners_count,r.participation_mode,r.reward_validity_mode,r.reward_valid_from,r.reward_valid_until,r.reward_valid_days,r.reservation_required,r.single_use,r.non_cumulative,r.status,r.drawn_at,(select count(*) from public.loyalty_customers c join lateral public.get_loyalty_customer_tier(c.id) t on true join public.loyalty_tiers eligible on eligible.establishment_id=r.establishment_id and eligible.tier_key=r.minimum_tier_key and eligible.active=true where c.establishment_id=r.establishment_id and c.created_at<=r.draw_at and t.sort_order>=eligible.sort_order),(select count(*) from public.loyalty_raffle_winners w where w.raffle_id=r.id),r.minimum_tier_key,r.ticket_multiplier_mode from public.loyalty_raffles r where r.establishment_id=p_establishment_id and public.user_has_establishment_access(p_establishment_id) order by r.draw_at desc; $$;

drop function if exists public.process_due_loyalty_raffles();
create or replace function public.process_due_loyalty_raffles() returns integer language plpgsql security definer set search_path=public as $$
declare r record;vf timestamptz;vu timestamptz;n integer:=0;begin
for r in select * from public.loyalty_raffles where status='SCHEDULED' and draw_at<=now() order by draw_at for update skip locked loop
perform public.ensure_default_loyalty_tiers(r.establishment_id);
insert into public.loyalty_raffle_entries(raffle_id,customer_id,tickets) select r.id,c.id,case when r.ticket_multiplier_mode='TIER' then greatest(1,coalesce(t.ticket_multiplier,1)) else 1 end from public.loyalty_customers c join lateral public.get_loyalty_customer_tier(c.id) t on true join public.loyalty_tiers eligible on eligible.establishment_id=c.establishment_id and eligible.tier_key=r.minimum_tier_key where c.establishment_id=r.establishment_id and c.created_at<=r.draw_at and t.sort_order>=eligible.sort_order on conflict(raffle_id,customer_id) do update set tickets=excluded.tickets;
if r.reward_validity_mode='DAYS_AFTER_DRAW' then vf:=r.draw_at;vu:=r.draw_at+make_interval(days=>r.reward_valid_days);else vf:=r.reward_valid_from;vu:=r.reward_valid_until;end if;
insert into public.loyalty_raffle_winners(raffle_id,customer_id,rank,prize_name,prize_description,valid_from,valid_until,reservation_required,single_use,non_cumulative) select r.id,e.customer_id,row_number() over(order by -ln(greatest(random(),1e-12))/greatest(e.tickets,1)),r.prize_name,r.prize_description,vf,vu,r.reservation_required,r.single_use,r.non_cumulative from public.loyalty_raffle_entries e where e.raffle_id=r.id order by -ln(greatest(random(),1e-12))/greatest(e.tickets,1) limit r.winners_count on conflict(raffle_id,customer_id) do nothing;
insert into public.loyalty_card_notifications(establishment_id,customer_id,title,message,type,expires_at) select r.establishment_id,w.customer_id,'🎉 Félicitations, vous avez gagné !','Vous avez gagné « '||w.prize_name||' ». Votre récompense est valable du '||to_char(w.valid_from,'DD/MM/YYYY')||' au '||to_char(w.valid_until,'DD/MM/YYYY')||case when w.reservation_required then '. Réservation obligatoire.' else '.' end,'REWARD',w.valid_until from public.loyalty_raffle_winners w where w.raffle_id=r.id;
update public.loyalty_raffle_winners set status='EXPIRED' where raffle_id=r.id and valid_until<now();
update public.loyalty_raffles set status='DRAWN',drawn_at=now(),eligibility_snapshot_at=now(),updated_at=now() where id=r.id;n:=n+1;end loop;return n;end;$$;

drop function if exists public.create_loyalty_raffle(uuid,text,text,text,text,timestamptz,timestamptz,integer,text,timestamptz,timestamptz,integer,boolean,boolean,boolean);
create or replace function public.create_loyalty_raffle(p_establishment_id uuid,p_title text,p_description text,p_prize_name text,p_prize_description text,p_starts_at timestamptz,p_draw_at timestamptz,p_winners_count integer,p_reward_validity_mode text,p_reward_valid_from timestamptz,p_reward_valid_until timestamptz,p_reward_valid_days integer,p_reservation_required boolean,p_single_use boolean,p_non_cumulative boolean,p_minimum_tier_key text default 'STANDARD',p_ticket_multiplier_mode text default 'TIER') returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid;begin if not(public.is_tapmarrakech_admin() or public.is_establishment_responsible(p_establishment_id)) then raise exception 'not_authorized';end if;perform public.ensure_default_loyalty_tiers(p_establishment_id);if not exists(select 1 from public.loyalty_tiers where establishment_id=p_establishment_id and tier_key=p_minimum_tier_key and active) then raise exception 'invalid_minimum_tier';end if;insert into public.loyalty_raffles(establishment_id,title,description,prize_name,prize_description,starts_at,draw_at,winners_count,reward_validity_mode,reward_valid_from,reward_valid_until,reward_valid_days,reservation_required,single_use,non_cumulative,status,created_by,minimum_tier_key,ticket_multiplier_mode) values(p_establishment_id,trim(p_title),nullif(trim(coalesce(p_description,'')),''),trim(p_prize_name),nullif(trim(coalesce(p_prize_description,'')),''),p_starts_at,p_draw_at,p_winners_count,p_reward_validity_mode,p_reward_valid_from,p_reward_valid_until,p_reward_valid_days,p_reservation_required,p_single_use,p_non_cumulative,'SCHEDULED',auth.uid(),p_minimum_tier_key,p_ticket_multiplier_mode) returning id into v_id;return v_id;end;$$;

revoke all on function public.get_loyalty_customer_tier(uuid) from public; grant execute on function public.get_loyalty_customer_tier(uuid) to anon,authenticated;
revoke all on function public.get_loyalty_tiers(uuid) from public; grant execute on function public.get_loyalty_tiers(uuid) to authenticated;
revoke all on function public.update_loyalty_tier(uuid,text,integer,integer,text,integer,boolean) from public; grant execute on function public.update_loyalty_tier(uuid,text,integer,integer,text,integer,boolean) to authenticated;
revoke all on function public.get_loyalty_raffles(uuid) from public; grant execute on function public.get_loyalty_raffles(uuid) to authenticated;