-- KELYANI: review bonuses, satisfaction feedback and WhatsApp/review context

alter table public.establishments add column if not exists tripadvisor_review_url text;

create table if not exists public.customer_reviews_claims (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.loyalty_customers(id) on delete cascade, establishment_id uuid not null references public.establishments(id) on delete cascade, platform text not null check (platform in ('google','tripadvisor')), claimed_at timestamptz not null default timezone('utc', now()), points_awarded integer not null default 0 check (points_awarded >= 0));
create unique index if not exists customer_reviews_claims_customer_platform on public.customer_reviews_claims(customer_id, platform);
alter table public.customer_reviews_claims enable row level security;
revoke all on public.customer_reviews_claims from anon, authenticated;

create table if not exists public.satisfaction_feedback (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.loyalty_customers(id) on delete cascade, establishment_id uuid not null references public.establishments(id) on delete cascade, rating integer not null check (rating between 1 and 5), comment text, points_awarded integer not null default 0 check (points_awarded >= 0), created_at timestamptz not null default timezone('utc', now()));
create index if not exists satisfaction_feedback_establishment_created on public.satisfaction_feedback(establishment_id, created_at desc);
alter table public.satisfaction_feedback enable row level security;
revoke all on public.satisfaction_feedback from anon, authenticated;

create or replace function public.get_public_loyalty_engagement_context(p_access_token uuid) returns table(customer_id uuid, establishment_id uuid, customer_name text, google_review_url text, tripadvisor_review_url text, whatsapp_number text, google_claimed boolean, tripadvisor_claimed boolean, feedback_submitted boolean) language sql stable security definer set search_path = public, pg_temp as $$ select c.id,c.establishment_id,trim(concat_ws(' ',c.first_name,c.last_name)),e.google_review_url,e.tripadvisor_review_url,e.whatsapp_number,exists(select 1 from public.customer_reviews_claims r where r.customer_id=c.id and r.platform='google'),exists(select 1 from public.customer_reviews_claims r where r.customer_id=c.id and r.platform='tripadvisor'),exists(select 1 from public.satisfaction_feedback f where f.customer_id=c.id) from public.loyalty_customer_links l join public.loyalty_customers c on c.id=l.customer_id join public.establishments e on e.id=c.establishment_id where l.access_token=p_access_token limit 1; $$;

create or replace function public.claim_public_loyalty_review_bonus(p_access_token uuid,p_platform text) returns table(success boolean,already_claimed boolean,points_awarded integer,points_balance integer) language plpgsql security definer set search_path = public, pg_temp as $$ declare v_customer public.loyalty_customers%rowtype; v_claim_id uuid; begin if p_platform not in ('google','tripadvisor') then raise exception 'invalid_review_platform'; end if; select c.* into v_customer from public.loyalty_customer_links l join public.loyalty_customers c on c.id=l.customer_id where l.access_token=p_access_token for update of c; if not found then raise exception 'invalid_access_token'; end if; if not exists(select 1 from public.establishments e where e.id=v_customer.establishment_id and ((p_platform='google' and nullif(trim(e.google_review_url),'') is not null) or (p_platform='tripadvisor' and nullif(trim(e.tripadvisor_review_url),'') is not null))) then raise exception 'review_platform_not_configured'; end if; begin insert into public.customer_reviews_claims(customer_id,establishment_id,platform,points_awarded) values(v_customer.id,v_customer.establishment_id,p_platform,0) returning id into v_claim_id; exception when unique_violation then return query select false,true,0,v_customer.points_balance; return; end; return query select true,false,0,v_customer.points_balance; end; $$;

create or replace function public.submit_public_loyalty_feedback(p_access_token uuid,p_rating integer,p_comment text default null) returns table(success boolean,points_awarded integer,points_balance integer) language plpgsql security definer set search_path = public, pg_temp as $$ declare v_customer public.loyalty_customers%rowtype; v_reward integer:=0; v_comment text:=nullif(trim(coalesce(p_comment,'')),''); v_feedback_id uuid; begin if p_rating<1 or p_rating>5 then raise exception 'invalid_feedback_rating'; end if; if length(coalesce(v_comment,''))>2000 then raise exception 'feedback_too_long'; end if; select c.* into v_customer from public.loyalty_customer_links l join public.loyalty_customers c on c.id=l.customer_id where l.access_token=p_access_token for update of c; if not found then raise exception 'invalid_access_token'; end if; if not exists(select 1 from public.satisfaction_feedback where customer_id=v_customer.id) then v_reward:=10; end if; insert into public.satisfaction_feedback(customer_id,establishment_id,rating,comment,points_awarded) values(v_customer.id,v_customer.establishment_id,p_rating,v_comment,v_reward) returning id into v_feedback_id; if v_reward>0 then update public.loyalty_customers as lc set points_balance=lc.points_balance+v_reward,total_points_earned=lc.total_points_earned+v_reward,updated_at=now() where lc.id=v_customer.id; insert into public.loyalty_transactions(establishment_id,customer_id,amount,points,type,description,transaction_reference) values(v_customer.establishment_id,v_customer.id,null,v_reward,'EARN','Bonus questionnaire satisfaction','feedback_bonus:'||v_feedback_id::text); end if; return query select true,v_reward,v_customer.points_balance+v_reward; end; $$;

create or replace function public.get_admin_satisfaction_feedback(p_establishment_id uuid,p_limit integer default 20) returns table(average_rating numeric,total_feedback integer,negative_count integer,id uuid,customer_id uuid,customer_name text,rating integer,comment text,points_awarded integer,created_at timestamptz) language sql stable security definer set search_path = public, pg_temp as $$ with authorized as (select 1 where public.user_has_establishment_access(p_establishment_id)),stats as (select coalesce(round(avg(f.rating)::numeric,2),0) average_rating,count(*)::integer total_feedback,count(*) filter(where f.rating<=2)::integer negative_count from public.satisfaction_feedback f where f.establishment_id=p_establishment_id and exists(select 1 from authorized)),rows as (select f.id,f.customer_id,trim(concat_ws(' ',c.first_name,c.last_name)) customer_name,f.rating,f.comment,f.points_awarded,f.created_at from public.satisfaction_feedback f join public.loyalty_customers c on c.id=f.customer_id where f.establishment_id=p_establishment_id and exists(select 1 from authorized) order by f.created_at desc limit greatest(1,least(coalesce(p_limit,20),100))) select s.average_rating,s.total_feedback,s.negative_count,r.id,r.customer_id,r.customer_name,r.rating,r.comment,r.points_awarded,r.created_at from stats s left join rows r on true order by r.created_at desc nulls last; $$;

revoke all on function public.get_public_loyalty_engagement_context(uuid) from public,anon,authenticated; grant execute on function public.get_public_loyalty_engagement_context(uuid) to anon,authenticated;
revoke all on function public.claim_public_loyalty_review_bonus(uuid,text) from public,anon,authenticated; grant execute on function public.claim_public_loyalty_review_bonus(uuid,text) to anon,authenticated;
revoke all on function public.submit_public_loyalty_feedback(uuid,integer,text) from public,anon,authenticated; grant execute on function public.submit_public_loyalty_feedback(uuid,integer,text) to anon,authenticated;
revoke all on function public.get_admin_satisfaction_feedback(uuid,integer) from public,anon; grant execute on function public.get_admin_satisfaction_feedback(uuid,integer) to authenticated;
