import type { LoyaltyBuilderConfig, LoyaltyTemplate } from './types';

export const RESTAURANT_TEMPLATES: LoyaltyTemplate[] = [
  {
    id: 'restaurant-elegant',
    name: 'Élégance',
    description: 'Sobre et raffiné',
    category: 'Élégant',
    primaryColor: '#173D32',
    secondaryColor: '#D3A84C',
    backgroundColor: '#F7F7F3',
    textColor: '#FFFFFF',
    buttonColor: '#173D32',
    borderRadius: 28,
    coverOverlay: 0.72,
    layout: 'editorial',
    stampStyle: 'circles',
  showQr: false,
  },
  {
    id: 'restaurant-gastronomic',
    name: 'Gastronomique',
    description: 'Chaleureux et authentique',
    category: 'Gastronomique',
    primaryColor: '#24150E',
    secondaryColor: '#D7A75A',
    backgroundColor: '#F4ECE4',
    textColor: '#FFFFFF',
    buttonColor: '#24150E',
    borderRadius: 24,
    coverOverlay: 0.66,
    layout: 'photo',
    stampStyle: 'circles',
  },
  {
    id: 'restaurant-modern',
    name: 'Moderne',
    description: 'Léger et contemporain',
    category: 'Moderne',
    primaryColor: '#F0E6D8',
    secondaryColor: '#173D32',
    backgroundColor: '#F7F7F3',
    textColor: '#173D32',
    buttonColor: '#173D32',
    borderRadius: 30,
    coverOverlay: 0.08,
    layout: 'split',
    stampStyle: 'squares',
  },
  {
    id: 'restaurant-minimal',
    name: 'Minimaliste',
    description: 'Épuré et moderne',
    category: 'Minimaliste',
    primaryColor: '#101112',
    secondaryColor: '#D3A84C',
    backgroundColor: '#F7F7F3',
    textColor: '#FFFFFF',
    buttonColor: '#101112',
    borderRadius: 22,
    coverOverlay: 0.58,
    layout: 'minimal',
    stampStyle: 'circles',
  },
  {
    id: 'restaurant-premium',
    name: 'Premium',
    description: 'Lumineux et chaleureux',
    category: 'Premium',
    primaryColor: '#EEE5D6',
    secondaryColor: '#B88738',
    backgroundColor: '#FBF8F1',
    textColor: '#1D211E',
    buttonColor: '#173D32',
    borderRadius: 32,
    coverOverlay: 0.12,
    layout: 'luxury',
    stampStyle: 'stars',
  },
  {
    id: 'restaurant-authentic',
    name: 'Authentique',
    description: 'Esprit brasserie',
    category: 'Authentique',
    primaryColor: '#5A321D',
    secondaryColor: '#F1C477',
    backgroundColor: '#F3E5D5',
    textColor: '#FFFFFF',
    buttonColor: '#5A321D',
    borderRadius: 24,
    coverOverlay: 0.5,
    layout: 'photo',
    stampStyle: 'circles',
  },
  {
    id: 'restaurant-brasserie',
    name: 'Brasserie',
    description: 'Chic et convivial',
    category: 'Premium',
    primaryColor: '#1E2430',
    secondaryColor: '#D8B36A',
    backgroundColor: '#F3F1EB',
    textColor: '#FFFFFF',
    buttonColor: '#1E2430',
    borderRadius: 26,
    coverOverlay: 0.64,
    layout: 'editorial',
    stampStyle: 'squares',
  },
  {
    id: 'restaurant-contemporary',
    name: 'Contemporain',
    description: 'Graphique et distinctif',
    category: 'Moderne',
    primaryColor: '#E8E1D6',
    secondaryColor: '#173D32',
    backgroundColor: '#FFFFFF',
    textColor: '#173D32',
    buttonColor: '#173D32',
    borderRadius: 34,
    coverOverlay: 0.08,
    layout: 'split',
    stampStyle: 'hearts',
  },
];

export const DEFAULT_BUILDER_CONFIG: LoyaltyBuilderConfig = {
  templateId: 'restaurant-elegant',
  loyaltyType: 'STAMP',
  primaryColor: '#173D32',
  secondaryColor: '#D3A84C',
  backgroundColor: '#F7F7F3',
  textColor: '#FFFFFF',
  buttonColor: '#173D32',
  borderRadius: 28,
  logoUrl: null,
  coverImageUrl: null,
  programName: 'Programme fidélité',
  cardTitle: 'Une cuisine, des moments mémorables.',
  cardSubtitle: 'Votre fidélité est récompensée.',
  progressText: 'Encore 4 visites pour votre récompense',
  rewardTitle: '8 tampons = 1 plat offert',
  rewardDescription: 'Votre fidélité est récompensée.',
  stampGoal: 8,
  rewardThreshold: 100,
  discountPercent: 10,
  rewardName: '1 plat offert',
  stampStyle: 'circles',
  published: false,
};
